In [4]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1']=pd.to_numeric(df['Feature1'],errors='coerce')
#df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)



   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [1]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # NaN
        'B': [4, None, 6]}  #Nan

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value,inplace=True)  #tranforming the original dataframe using 'inplace'because FILLNA create new df.
print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]) .reshape(-1,1) # Error: X should be 2D so using reshape to convert from 1d to 2d
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


In [ ]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1)  #  Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
#y = ['yes', 'no', 'yes']  # Error: Labels should be numeric
y=[1,0,1]
model = LogisticRegression()
model.fit(X, y)
print(model.predict([[1, 3]]))

In [12]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])  #category should be 2d
print(encoded)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [15]:
#6.
from sklearn.model_selection import train_test_split
X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0,1] #y values should be same length of X
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train)
print(y_train)


[[1, 2], [3, 4], [7, 8]]
[0, 1, 1]


In [16]:
#7.
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

encoder=LabelEncoder()
y_encoded=encoder.fit_transform(y_train)
print(y_encoded)
model = LogisticRegression()
model.fit(X_train, y_encoded)
model.predict([[3,5]])


[1 0 1]


array([1])

In [18]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])
imputer=SimpleImputer(strategy='mean') 
x_mod=imputer.fit_transform(X_train)
print(x_mod)
model = LinearRegression()
model.fit(x_mod, y_train)  


[[1. 2.]
 [3. 4.]
 [5. 6.]]


LinearRegression()

In [ ]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


In [30]:
#Ans:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)  # Convert to numbers
print(y_train_encoded)
model.fit(X_train, y_train_encoded)
print('Final Prediction:',model.predict([[2, 3]]))  

[1 0 1]
final [1]


In [31]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


[0]
